<<<<<<< HEAD
[[redirects]]
from = "/*"
to = "/prac.html"
status = 200
=======
[[redirects]]
from = "/*"
to = "/prac.html"
status = 200
=======
[[redirects]]
from = "/*"
to = "/contactpage.html"
status = 200
=======
[[redirects]]
from = "/*"
to = "/contact.html"
status = 200


